### ISSUE TITLE
Pi 4

### ISSUE THREAD

**Issue by pfaffenrodt** [voldedore/docker-rpi-omv#2]
> I recently stopped maintaining this repo due to a lack of time and RPI is not a proper idea for NAS, it's slow and the solution is somehow 'unstable'.

What about Pi 4 with usb 3.0 ? Do you have an opinion?

**Comment by voldedore** [comment]
Since the new one (Pi 4) has been resolved the bus sharing issue, this may bring back a really vivid hope to those who want an inexpensive solution for a personal NAS.

But this container approach (powered by docker) is hard to maintain/configure things so I strongly recommend you to check out the official OMV sourceforge, they have a dedicated image for Rasp Pi 4.

https://sourceforge.net/projects/openmediavault/files/Raspberry%20Pi%20images/

I DID switch from this container approach back to the traditional one and was happy for it.

**Comment by pfaffenrodt** [comment]
Ok, I am very grateful with your recommendation.
